### ISSUE TITLE
Sidebar breaking on hover.

### ISSUE THREAD

**Issue by krushna06** [Bot-Rakshit/bm_frontend#117]
Sidebar breaking when hover

https://github.com/user-attachments/assets/647c5efb-be4a-49ab-ba04-efcf5b4bcc61

**Comment by krushna06** [comment]
Working on a fix

**Comment by krushna06** [comment]
Fix pr https://github.com/Bot-Rakshit/bm_frontend/pull/118

**Comment by krushna06** [comment]
@all-contributors please add @krushna06 as Maintenance for https://github.com/Bot-Rakshit/bm_frontend/pull/118

**Comment by krushna06** [comment]
I can't view your recording. Also I'm having the same issue on brave.

**Comment by govindup63** [comment]
i am having the same issue
in chrome on mac

**Comment by krushna06** [comment]
Look carefully in your own video. Theres 3.
1. Sidebar
2. Middle (the broken part)
3. The community stats
https://i.imgur.com/cPhcQyo.png

**Comment by krushna06** [comment]
It hasn't been fixed yet, please check again.
