### ISSUE TITLE
Fix logout button on mobile

### ISSUE THREAD

**Issue by Prathamesh-B** [Bot-Rakshit/bm_frontend#120]
# Move the button to the bottom 

![www bmsamay com_chesstutorials_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 eyJpZCI6ImFkMDQ1ZjQzLTUxOTYtNGM4My1hNWU5LWYxNGE2ODZhN2UzMSIsInZlcmlmaWNhdGlvbkNvZGUiOiJodGdzc2NkdHB5NyIsImNoZXNzVXNlcm5hbWUiOiJQcmF0aGF](https://github.com/user-attachments/assets/2f178ef7-e7c7-430a-a12b-d3640bdd2e15)

**Comment by vatan45** [comment]
make i take this...?

**Comment by Prathamesh-B** [comment]
Certainly! I'll assign it to you.

**Comment by krushna06** [comment]
pr made https://github.com/Bot-Rakshit/bm_frontend/pull/121
clsoe this issue
