### ISSUE TITLE
Open Chess.com profile on user name click

### ISSUE THREAD

**Issue by ARSHIL1804** [Bot-Rakshit/bm_frontend#52]
How about adding a clickable link in the user name that will open the chess.com profile of that user on a new tab?

![image](https://github.com/user-attachments/assets/4fef6b06-c8a2-49b1-b413-41996cf33e2a)

**Comment by ARSHIL1804** [comment]
@Bot-Rakshit we can directly add the link in frontend no?

**Comment by ARSHIL1804** [comment]
> I'll make a backend route to add more information when hovered for later.
Ohh, that would be cool 👍 

> You can go ahead and make a pr to make the usernames clickables for now 
Sure 👍

**Comment by Prathamesh-B** [comment]
How do we work on the community page in development mode? Whenever I try to open it, it doesn't load due to CORS errors. I would like to know a workaround for this issue.

**Comment by Prathamesh-B** [comment]
Thanks for the suggestion. I’ll check out the backend too. @Bot-Rakshit

**Comment by ARSHIL1804** [comment]
@Prathamesh-B 
Or go to the original website and in localhost storage, you can find dahsboardData.
![image](https://github.com/user-attachments/assets/4f8ea2f9-2e24-462f-a5ae-2a2fef9a815c)
Could you copy this and paste it into your vite localhost storage?
Also in community.tsx file update UPDATE_INTERVAL value to 600000000(some random high value)
CC: @Bot-Rakshit
