### ISSUE TITLE
User Information Overlay Issue on Small/Vertical Screens

### ISSUE THREAD

**Issue by Sama-004** [Bot-Rakshit/bm_frontend#75]
![image](https://github.com/user-attachments/assets/be293e8e-f74a-453f-a1a7-c53c66410e3c)

### Steps to Reproduce

- Open https://www.bmsamay.com/community on a small screen or resize the browser window to a vertical layout.
- Hover over the username on any card 
- Observe that the black div containing the user information is being overlapped by the card elements.

**Comment by Prathamesh-B** [comment]
ill do this
