### ISSUE TITLE
Wanna implement botbyte AI

### ISSUE THREAD

**Issue by sanketbagad** [Bot-Rakshit/bm_frontend#9]
Users can interact with the AI and ask their questions there. As a member of BM Army, you will receive it as a gift for free for a lifetime.

**Comment by ashwaniverma-github** [comment]
To build this feature , we will have to use open ai API and any gpt model and train that bot on the basis of chess .

**Comment by sanketbagad** [comment]
Will take care of that, don't worry😊

**Comment by manjotsk** [comment]
We'll include this in next iteration right @Bot-Rakshit? This can be a useful feature. Need to see what it can cost us. @sanketbagad . For now we can close the PR. Will reopen when we'll plan to include this.

**Comment by manjotsk** [comment]
> "As a member of BM Army, you will receive it as a gift for free for a lifetime."
If that's the case @Bot-Rakshit discuss this with @sanketbagad
